### ISSUE TITLE
Neoforge 1.20.1 "not a valid mod file"

### ISSUE THREAD

**Issue by Snooziepup** [Numelon-Softworks/ThreatenGL#13]
on trying to start the game with the mod Neoforge reports that it isn't a valid mod file :(

**Comment by Richy-Z** [comment]
Hello! 
I'm sorry to see that the mod is being frustrating on NeoForge 1.20.1. 😔

Would you mind clarifying what you mean by it saying it's "not a valid mod file"? E.g. does a window pop up saying that there's an error with the mod? Does Minecraft just quit unexpectedly? Do you see a long piece of text after Minecraft unexpectedly closed, a crash log?

Being as descriptive as possible will help me help you :)

**Comment by Snooziepup** [comment]
hi, an error screen pops up with the filename of the mod and the message, and a button to proceed to the menu screen but it halts the loading of the rest of the mods so theyre not actually loaded when on the menu

**Comment by Richy-Z** [comment]
Ohhh, I understand it now, the NeoForge mod warning screen.

Are you using the default Minecraft Launcher, MultiMC, Prism Launcher, the Modrinth App, the CurseForge app, etc? (Which launcher?)

**Comment by Snooziepup** [comment]
I'm using Prism Launcher.

**Comment by ashley-graves** [comment]
same issue here, was planning on adding this to my modpack

**Comment by Richy-Z** [comment]
Thanks for sharing! I thought this issue was resolved haha 😅 I'll look into it

**Comment by ashley-graves** [comment]
> Thanks for sharing! I thought this issue was resolved haha 😅 I'll look into it

here's the error, might help ya out a bit
```
[05 Aug 2024 15:34:54.214] [main/ERROR] [net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Locator {mods folder locator at /home/ashley/.local/share/PrismLauncher/instances/posspack/.minecraft/mods} found an invalid mod file net.minecraftforge.fml.loading.moddiscovery.ModFileInfo@29c5ee1d
net.minecraftforge.fml.loading.moddiscovery.InvalidModFileException: Missing required field mandatory in dependency (threatengl-neoforge-1.3.2-beta.1.jar)
        at net.minecraftforge.fml.loading.moddiscovery.ModInfo$ModVersion.lambda$new$1(ModInfo.java:217) ~[loader-47.2.2.jar:47.2]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at net.minecraftforge.fml.loading.moddiscovery.ModInfo$ModVersion.<init>(ModInfo.java:217) ~[loader-47.2.2.jar:47.2]
        at net.minecraftforge.fml.loading.moddiscovery.ModInfo.lambda$new$8(ModInfo.java:100) ~[loader-47.2.2.jar:47.2]
```

**Comment by Richy-Z** [comment]
Thank you for sharing your error. A new version of ThreatenGL will be posted in a bit, I've found out that Forge has changed their mods.toml file structure.

**Comment by Richy-Z** [comment]
ThreatenGL 1.3.3 will be posted on Modrinth as soon as it finishes building 🤗
Thanks for reporting the issue!

**Comment by FluffyWolfLord** [comment]
yeah im getting the issue on latest version

**Comment by Richy-Z** [comment]
This is still on NeoForge 1.20.1 or 1.20.x?

**Comment by Endri2015** [comment]
forge 1.20.1

**Comment by Endri2015** [comment]
not neoforge

**Comment by LuizLoyola** [comment]
Error still exists:
- Minecraft 1.20.1
- Forge 47.3.5
- `threatengl-neoforge-1.3.3-release.1.jar`

**Comment by LuizLoyola** [comment]
Just realized I'm using the NeoForge version on Forge. This is the featured version for Forge on Modrinth.
Using the correct version found on the versions page, it works.

![image](https://github.com/user-attachments/assets/aa654e56-3ccf-45bb-9315-eace9376e667)

**Comment by Richy-Z** [comment]
@LuizLoyola Modrinth automatically marked the NeoForge upload as Forge haha, sorry that's an error on my part as I didn't notice.

**Comment by Richy-Z** [comment]
The mislabelling on Modrinth has been corrected. However the mod still doesn't work on **NeoForge** either?

**Comment by natpalmer-e4o4** [comment]
I can confirm that the issue still exists when using the NeoForge version of the mod on 1.20.1 through Prism Launcher


Oddly enough, using the Forge version allows everything to load correctly.

**Comment by Richy-Z** [comment]
Thank you all for reporting back on this issue, and sorry for not keeping up with this thread as I took a break to focus on other things.

The reason this entire issue is happening in the first place is because at one point the mod was updated to fix another similar issue related to NeoForge. It looked like NeoForge updated their mod metadata file structure but now it looks like that never happened - its quite unclear at the moment. I'll have to properly research how NeoForge expects this file to look like and I'll get back to you all soon.

**Comment by Richy-Z** [comment]
Hello, I just tested this issue using a fresh installation of NeoForge 1.20.1 (version 47.1.106) and looks like there may have been a regression issue (particularly with how the mod toml file worked or something. Since the mod works with the latest version and this issue is quite old and stale, I will be marking this as complete.

If you are still encountering this issue, please feel free to leave a comment here and re-open the issue.
